name: 'Andy Andrea'
description: 'Andy Andrea'
url: 'http://andycandrea.github.io'

paginate: 5
highlighter: rouge
markdown: kramdown

gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jemoji

comments: true

sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: 'Andy Andrea'
keywords: 'andy, andrea, ruby, rails, durham, nc, web'

repo: http://github.com/andycandrea/andycandrea.github.io

# Author settings
author:
  name      : Andy Andrea
  job       : Web Developer
  bio       : 'Durham, NC-based dev, astronomy geek and foodie.'
  thumb     : /images/aa.jpeg
  email     : andrewcandrea@gmail.com
  url       : http://andycandrea.github.io
  github    : http://github.com/andycandrea
  linkedin  : http://linkedin.com/in/andycandrea

# navbar pages
navbar:
  - slug: about
    title: About

exclude: ['gulp', 'node_modules', 'bower', 'bower_components', 'config.rb', 'src', 'Gemfile', 'Gemfile.lock', '.rvmrc', '.rbenv-version', 'package.json', 'gulpfile.js', 'README.md', 'Rakefile', 'changelog.md']
