name: "Andy's Blog"
description: "Andy's Viget Internship Blog"
url: "http://andycandrea.github.io"

paginate: 10
highlighter: pygments
markdown: kramdown

gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
